import type { Badge, BadgeWithEarned } from './types'

/**
 * Oblique, per-badge hints shown for LOCKED badges only. Written in the same
 * wry, teasing voice as the earned-badge descriptions — commentary, not
 * instructions — and keyed by slug (not criteria_type) so every badge gets
 * copy written for what it actually is, not a shared template.
 */
const BADGE_TEASERS: Record<string, string> = {
  'first-review': "Everybody's got a first time. Yours hasn't happened yet.",
  'review-count-5': "Five in, and you're still very much in the honeymoon phase.",
  'review-count-10': "Past the beginner arc. Not yet a main character.",
  'review-count-25': 'Enough reviews that people should probably start asking your opinion.',
  'review-count-50': 'At some point this stops being a hobby and starts being a lifestyle.',
  'size-sampler': 'Small, medium, large, jumbo — commitment issues, but for wing sizes.',
  'wing-veteran': "You've put in enough reps to have Opinions, capital O.",
  'century-club': 'Triple digits. Somebody should probably check on you.',

  '2026-chicken-wing-crawl-ottawa-rsvp': "Say the word. The route's waiting on you.",
  '2026-dc-chicken-wing-crawl-rsvp': 'Two words. You already know which ones.',
  '2026-dc-chicken-wing-crawl-early': 'Beat literally everyone else there. Set an alarm.',
  '2026-chicken-wing-crawl-ottawa-early': 'Somebody has to be first through the door. Might as well be you.',
  '2026-dc-chicken-wing-crawl-social': 'A solo RSVP is fine. This one wants a crowd.',
  '2026-chicken-wing-crawl-ottawa-social': 'One person does not fill a canoe. Bring friends.',
  '2026-chicken-wing-crawl-ottawa-first': 'The route has a first stop. Go stand in it.',
  '2026-dc-chicken-wing-crawl-first': "Somewhere on the route, a first stop is waiting to be checked into.",
  '2026-chicken-wing-crawl-ottawa-two': 'Two stops. Like the coffee order, but wings.',
  '2026-dc-chicken-wing-crawl-two': "Barely broken a sweat — a couple of stops in.",
  '2026-dc-chicken-wing-crawl-three': "Momentum's a real thing on this route. You'll feel it a few stops deep.",
  '2026-chicken-wing-crawl-ottawa-three': 'Hockey people already know exactly what number this is about.',
  '2026-chicken-wing-crawl-ottawa-four': 'The route gets long in the middle. Keep carrying on.',
  '2026-dc-chicken-wing-crawl-four': 'Deep enough in that people start asking you for recommendations.',
  '2026-chicken-wing-crawl-ottawa-review': "Somebody's got to go on the record. Might as well be you.",
  '2026-dc-chicken-wing-crawl-review': 'The route deserves at least one hot take from you, in writing.',
  '2026-dc-chicken-wing-crawl-all-reviews': "Checking in isn't the whole job. Finish what you started.",
  '2026-chicken-wing-crawl-ottawa-all-reviews': 'Keep the official record complete. Every stop gets its say.',
  '2026-chicken-wing-crawl-ottawa-champion': 'Every single stop. No skipping, no shortcuts.',
  '2026-dc-chicken-wing-crawl-champion': 'The whole route, start to finish. No half measures.',

  scout: 'Your usual spot is fine. It is also not the only spot.',
  explorer: "The map is bigger than the corner of it you've been sticking to.",
  cartographer: "At some point you'll know this map better than whoever drew it.",
  'district-mapper': "You're not exploring anymore. You're annexing.",

  'flavor-curious': "The menu has more than one line on it. Start reading further down.",
  'sauce-scholar': "You've clearly stopped ordering the same thing out of habit.",
  'flavor-professor': "At this point you could grade other people's flavor choices.",

  'lemon-pepper-legend': "This one's earned at the counter, not in the write-up.",
  'crispy-devotee': "This one's earned in the write-up, not at the counter.",
  'ranch-defender': 'No defense needed in writing. Just order the thing.',
  'bone-in-purist': "Ordering it isn't enough — you have to actually say something about it.",
  'blue-cheese-believer': 'Believing quietly does not count. Put it in writing.',
  'heat-survivor': 'Somewhere on the menu is a flavor with warning-label energy. Order that one.',
  'the-essayist': 'Some people leave a rating. You leave a thesis.',
  'short-and-sweet': 'Say it and get out. Nobody needs the director\'s cut.',
  'scorched-earth': 'Give a spot a rating that ends the conversation entirely.',

  'first-crawl': "Everybody's got a first list in them. Time to let yours out.",
  'first-voice': "The comment section is right there. Use your words.",
  'not-impressed': 'Give a spot a rating that says plenty without saying much.',
  'loud-mouth': "You clearly have thoughts. Keep sharing them.",
  'thread-lord': 'At some point the comment section just becomes your section.',
  'easy-grader': "Somebody's out here handing out great scores like candy. Could be you.",
  'crawl-curator': 'A crawl with two stops on it is a suggestion. Make it a real list.',
  'rookie-rater': 'Whole numbers only. No decimals, not even once.',
  'crawl-crowd-pleaser': 'Make a crawl good enough that people actually hit like.',
  'decimal-daredevil': 'Whole numbers are for cowards. Live a little.',
  'crawl-prolific': 'One list is a hobby. A stack of them is a whole personality.',
  'crawl-spoke-up': 'Somebody made a crawl. You have opinions about it. Say so.',
  'crawl-yapper': 'You clearly did not stop at just one comment.',
  'crawl-hot-take': "Tell a crawl exactly how mid you think it is. Don't hold back.",
  'harsh-critic': 'Keep your average score somewhere near rock bottom for a while.',
  'high-standards': 'Keep your average score somewhere near flawless for a while.',
  'crawl-hype-beast': 'Hype a crawl up like it just dropped a new album.',
  'crawl-just-a-gif': 'Words are optional. A GIF says plenty.',
  'perfect-ten': 'Somewhere out there is a spot worth the absolute max score. Find it.',
  'crawl-reply-guy': "Somebody else's crawl. Your comment. You know how this works.",
  'rate-tough-crowd': 'Give a spot a low score and let them sit with it.',
  'rate-cold-blooded': "Give a spot the actual worst score possible. Don't blink.",
  'rate-serial-hater': 'Rack up a run of reviews that are all pretty unkind.',
  'rate-easy-lover': 'Rack up a run of reviews that all read like fan mail.',
  'takeout-king': 'Skip the dine-in enough times and it starts to count for something.',
  'to-go-loyalist': 'At this point, eating in is basically a foreign concept to you.',
  regular: 'Go back to the same spot enough times and they start to know your order.',
  'day-one': 'Loyalty like this deserves a title, not just a punch card.',
  'jumbo-fan': "This one's decided at the counter, not in your write-up.",

  'canadiana-confederation': 'Every Canadian kid learns this year before they learn their own postal code.',
  'canadiana-canada-day': 'Fireworks, a flag, and a rating that happens to match the date on the calendar.',
  'canadiana-skateway': "The world's longest skating rink has a length. This badge has the same number.",
  'canadiana-great-one': 'One jersey number. Every hockey fan in the country already has it memorized.',
  'canadiana-loonie': 'One coin, one dollar, one very specific rating.',
  'canadiana-toonie': 'Twice the coin. Twice the number.',
  'canadiana-poutine': "You don't have to order it. Just bring it up.",
  'canadiana-extra-u': 'Spell something the way we do up here, not the way they do down south.',
  'canadiana-sorry': 'Apologizing for nothing in particular is basically a national pastime.',
  'canadiana-tapped': 'Every spring, something very Canadian starts running through the trees.',
  'canadiana-rink-rat': 'This city loses its mind over one sport (and one team) every winter.',
  'canadiana-timmies': "You don't have to actually go. Just bring it up.",
  'canadiana-honey-garlic': "You don't have to write a treaty about it. Just order it.",
}

export function badgeTeaser(badge: Badge | BadgeWithEarned): string {
  return BADGE_TEASERS[badge.slug] ?? `There's a specific way to unlock "${badge.name}" — you'll have to find it.`
}
